/*
    WARNING:

    This file is auto-generated from C# class `UCB.JapanCimzia.API.Controllers.OrdersController`
    Please do not edit this file by hand. It's going to be automatically overriden after each build of
    `UCB.JapanCimzia.TSGeneration` project.
*/

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs/Observable';
import { BaseUriService} from './baseuri.service';



@Injectable()
export class APIOrdersService {

    
    constructor(
        private http: HttpClient,
        private baseUriService: BaseUriService) {
    }


    public getOrders(): Observable<api.OrderMessage[]> {
        const uri = this.baseUriService.getBaseUri() + `/api/orders`;
        return this.http.get<api.OrderMessage[]>(uri);
    }
  
    

    public addOrder(orderMessage:api.OrderMessage): Observable<object> {
        const uri = this.baseUriService.getBaseUri() + `/api/orders`;
        return this.http.post(uri, orderMessage);
    }
  
    

    public deleteOrder(orderId:number): Observable<object> {
        const uri = this.baseUriService.getBaseUri() + `/api/orders/${orderId}`;
        return this.http.delete(uri);
    }
  
    

    public updateOrder(orderId:number, orderMessage:api.OrderMessage): Observable<api.OrderMessage> {
        const uri = this.baseUriService.getBaseUri() + `/api/orders/${orderId}`;
        return this.http.put<api.OrderMessage>(uri, orderMessage);
    }
  
    
}
